### ISSUE TITLE
Make this thing actually usable

### ISSUE THREAD

**Issue by RadValentin** [RadValentin/rss-2-alexa-flash-briefing-json#1]
## TODO

- [x] Store feed in memory and only refresh it every minute (not on every request)
- [ ] Return only complete sentences to clients (don't terminate sentences on ...)
  - Use [sbd](https://github.com/Tessmore/sbd) to identify sentences
- [ ] Run the feed through a TTS service that doesn't sound like a robot and return audio in JSON
  - Amazon Polly?
  - http://ttsreader.com/ UK female voice has good diction, strive for similar results here
- [ ] Drop RSS and instead crawl the website for text content (new repo)
